Start Migration
2
>>>>>>>>>>>>>>>>>>>>>>>>>>Load Balance<<<<<<<<<<<<<<<<<<<<<<<<<
Migration method: 2
Traceback (most recent call last):
  File "../../case_hotness_balance.py", line 13, in <module>
    success_send = apply_migration_plan(migration_candidates, rc, server_links, int(sys.argv[1]))
  File "/data/jinghuan/KVRocks-Rebalancer-cpp/utils/utils.py", line 54, in apply_migration_plan
    migrate_reply = cluster_link.execute_command(*cmd.split())
  File "/usr/local/lib/python3.8/dist-packages/redis_py_cluster-2.1.3-py3.8.egg/rediscluster/client.py", line 556, in execute_command
  File "/usr/local/lib/python3.8/dist-packages/redis_py_cluster-2.1.3-py3.8.egg/rediscluster/client.py", line 722, in _execute_command
rediscluster.exceptions.ClusterError: TTL exhausted.
Could not connect to Redis at 127.0.0.1:40001: Connection refused
Migration Finished
